[package]
name = "markdown_html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
horrorshow = "0.8.4"
pulldown-cmark = "0.9.3"
